# Generated by Django 5.1.6 on 2025-03-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=100)),
                ('Teacher', models.CharField(max_length=100)),
            ],
        ),
    ]
